fix(transformer): include anonymous exports
Igorbek/typescript-plugin-styled-components pull request #367
Opened 2021-03-28 16:39 UTC by kirstymullen

This change ensures that the transformer also picks up anonymous exports:
`export default styled(Thing)`

It might be best practice to ensure all exports are named, but I'm working in a large project that already has a significant amount of  these.

Hope this is the best way to solve this. It looks like the plugin did support this at some point, as getDisplayNameFromNode is already able to handle it.

2021-03-31 07:23 UTC, kirstymullen commented
Hey @Igorbek - would you be able to review this PR please? Thanks

2021-03-31 16:44 UTC, Igorbek commented
Hey sorry, didn't notice a pr was created. Let me see it. The screenshot changes seem suspicious at first glance.

2021-04-01 08:12 UTC, kirstymullen commented
Thanks @Igorbek. The snapshots are what I'd expect given my change, but let me know what you think. Cheers.

2021-04-01 21:53 UTC, Igorbek approved these changes

2021-04-01 22:22 UTC, Igorbek requested changes
Could you please add a note to the `CHANGELOG.md` file.

2021-04-02 13:36 UTC, kirstymullen commented
> Could you please add a note to the `CHANGELOG.md` file.

Thanks for reviewing @Igorbek! I've updated the changelog file.

2021-04-02 19:50 UTC, Igorbek approved these changes

2021-04-02 19:50 UTC, merged

2021-04-07 06:01 UTC, Igorbek commented
It's now been released https://github.com/Igorbek/typescript-plugin-styled-components/releases/tag/1.5.0
Thank you for the contribution @kirstymullen!

2021-04-07 07:25 UTC, kirstymullen commented
Thanks @Igorbek, I appreciate the effort you've put into this plugin. I've sent you some coffees! :coffee: