Remove deprecated `.extend` transformation pattern
Igorbek/typescript-plugin-styled-components pull request #370
Opened 2021-03-30 23:57 UTC by renatonouman

This PR makes styled-components `.extend` pattern optional, since it has been deprecated in v4(styled-components/styled-components#1908).

Moreover, appending `.withConfig` to other extend methods might break unrelated code, i.e. https://github.com/Igorbek/typescript-plugin-styled-components/issues/33

2021-03-31 00:03 UTC, renatonouman commented
@Igorbek any instructions on how to add this to readme and release notes?

2021-04-01 22:21 UTC, Igorbek requested changes
Thank you for the contribution! Could you please add a line to the 'unreleased' section to the `CHANGELOG.md` file. I just created it.

2021-04-01 22:21 UTC, Igorbek commented on src/createTransformer.ts
> +        if (isStyledExtendIdentifier(node.name.text, identifiers)) {
```suggestion
        if (isStyledExtendIdentifier(node.name.text, identifiers)
            && isValidComponent(node.expression)) {
```

we still need to check that it is a valid component.

2021-04-01 23:10 UTC, renatonouman commented
Thank you for reviewing this so quickly. Changes made as requested!

2021-04-02 19:42 UTC, Igorbek requested changes

2021-04-02 19:42 UTC, Igorbek commented on CHANGELOG.md
> +- remove deprecated .extend transformation pattern (fix #48 in #152)
```suggestion
- remove deprecated .extend transformation pattern (fix #48 in #370)
```

2021-04-02 19:42 UTC, Igorbek approved these changes

2021-04-02 19:52 UTC, Igorbek commented
Sorry, @renatonouman another pr got merged, please resolve conflicts and update snapshots.

2021-04-02 20:52 UTC, renatonouman commented on CHANGELOG.md
> +- remove deprecated .extend transformation pattern (fix #48 in #152)
Oh, sorry about this. Fixed!

2021-04-02 20:59 UTC, renatonouman commented
Done @Igorbek

2021-04-02 21:05 UTC, Igorbek approved these changes

2021-04-02 21:07 UTC, merged

2021-04-02 21:23 UTC, renatonouman commented
Glad to contribute! Thanks for the review and merge!

2021-04-06 22:22 UTC, renatonouman commented
Hey @Igorbek! I just want to check with you when do you plan on releasing the next version?
Thanks!

2021-04-06 22:59 UTC, Igorbek commented
I started preparing it lately, but got interrupted with other stuff, as usual. I'll try to release it tonight. Sorry for inconvenience.

2021-04-07 06:01 UTC, Igorbek commented
It's now been released https://github.com/Igorbek/typescript-plugin-styled-components/releases/tag/1.5.0
Thank you for the contribution @renatonouman!

2021-04-08 14:43 UTC, renatonouman commented
Thank you for the release @Igorbek.
Using the new version in my project already!