Update Typescript to v5
Igorbek/typescript-plugin-styled-components pull request #711
Opened 2023-04-04 05:30 UTC by janpe

2023-04-04 15:58 UTC, Igorbek commented
It seems the version of the node in the GitHub actions has to be updated to `>=12.20`.

2023-04-05 05:39 UTC, janpe commented
> It seems the version of the node in the GitHub actions has to be updated to `>=12.20`.

Where are these pipelines configure? Can't seem to find anything about them in the repository. Running in Azure, not Github?

2023-05-18 21:09 UTC, probablyup commented
It might be easier to just switch to normal Github actions? I could whip up a PR for that @Igorbek if you're interested

2023-05-19 20:47 UTC, Igorbek requested changes
I think it would be reasonable to keep the support of 4.x along with the new 5.x

2023-05-19 20:47 UTC, Igorbek commented on package.json
> +        "typescript": "^5.0.0"
it'd be nice to keep 4.x support `4 || 5`

2023-05-19 20:47 UTC, Igorbek commented on src/createTransformer.ts
> +                context.factory.updateExportAssignment(node, node.modifiers, expression);
is it possible to support both - old and new APIs? maybe pass TS version parameter to the config

2023-05-19 20:57 UTC, Igorbek commented
@janpe please take a look - the tests are failing now
now you can see the tests in the GH actions (thanks to @probablyup )

2023-06-02 17:54 UTC, Igorbek commented
superseded by #713

2023-06-02 17:54 UTC, closed without merging